### ISSUE TITLE
Feature Request: support for LaTex with mathjax

### ISSUE THREAD

**Issue by Novite5** [corollari/ankiTab#13]
Now AnkiTab cannot display cards contains latex formals.
Wish support it in near future.
Thank you!

**Comment by Novite5** [comment]
Sorry! I found AnkiTab can display LaTex, only the mathjax format doesn't support.

**Comment by corollari** [comment]
If you send me some cards that include MathJax cards for testing I can include MathJax functionality into ankiTab (should be pretty easy as it's only including more scripts).

**Comment by Novite5** [comment]
Sorry! I've already changed all the cards to LaTex. However, I found AnkiTab doesn't support LaTex shorthand.

**Comment by masteranza** [comment]
Hi, @corollari I'd love to see this feature implemented (MathJax).
I can provide you with example cards, but it's rather simple - just create a card with, say:
`\( f(x) = x^2 \)`

MathJax is rendered live and higher resolution than LaTeX, plus my workflow allows me to use only MathJax.

**Comment by corollari** [comment]
@masteranza Noted. I'll keep it here till I have time to work on it.

**Comment by annargrs** [comment]
same here, I cannot really use the plugin without it.

**Comment by corollari** [comment]
Just added MathJax support, it's currently working on branch `mathjax`. Not going to push the next version live yet because:
- Firefox: I have to make sure that all the new files added comply with Firefox policies (including tracking down the all the dependencies of MathJax in it's unminimized form, checking if all the versions are a "stable release", checking licenses...)
- Chrome: I have tested this version with my usual set of testing cards but i'm not 100% sure that I'm not adding a new edge case that causes some special type of cards to crash as I haven't been able to review all of the code on the new mathjax files. If someone is willing to test it and reports that it's working I'll push it live.

Hope it's worth the wait @Novite5 and @masteranza. If there's anything else just feel free to create a new issue :)

**Comment by annargrs** [comment]
@corollari I just tested it, works fine for my cards (simple basic model). Thanks a lot!

**Comment by masteranza** [comment]
@corollari It works great! Thank you for making this happen!

**Comment by corollari** [comment]
@Novite5 @annargrs Thanks, I'll push it live later today!

**Comment by corollari** [comment]
Published! Should be available in the chrome store in a few hours.

**Comment by Novite5** [comment]
Great work! Thank you!
