### ISSUE TITLE
Link to Firefox package not working

### ISSUE THREAD

**Issue by lieuzhenghong** [corollari/ankiTab#17]
Have seen issue #6 and #3. The link given in #3 [[post here]](https://github.com/corollari/ankiTab/issues/3#issuecomment-419745618) is no longer working, and neither is the one in `README.md`.

Where can I download the package?

Thanks very much.

Sincerely
Zhenghong

**Comment by corollari** [comment]
I'll look into it right now. Thanks for the heads up :+1:

**Comment by corollari** [comment]
After looking at it more closely, it seems the extension was banned from the firefox store 15 days ago due to two reasons unrelated to #3 and #6:
1. Use of an alpha release of bootstrap (it seems developers are only allowed to use stable versions [1])
2. Use of a slightly modified copy of jquery

Regarding reason 2, this addon removed all dependencies on jquery, and jquery itself, about 7 months ago (see a9fabd1c45a81dec28b5c6e5788c1a61993a77cf) so I'm not really sure what to make of this.

Anyway, I'll update bootstrap to a stable version and resubmit the extension while sacrificing a lamb to appease the gods.

[1] According to the rules "Note that non-release versions of third-party libraries are not accepted.", so, is an alpha release considered a non-release version? It seems so.

**Comment by corollari** [comment]
Closing because this was solved 5 days ago.
